require('presence').setup({
    auto_update         = true,
    neovim_image_text   = 'neovim',
    main_image          = 'neovim',
    client_id           = '793271441293967371',
    log_level           = nil,
    debounce_timeout    = 3,
    enable_line_number  = true,
    blacklist           = {},
    buttons             = false,
    file_assets         = {},
    show_time           = true,
    editing_text        = 'Editing',
    file_explorer_text  = 'Browsing',
    git_commit_text     = 'Committing changes',
    plugin_manager_text = 'Managing plugins',
    reading_text        = 'Reading',
    workspace_text      = 'Working',
    line_number_text    = 'Line %s out of %s',
})
